CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(async-function-execution C CXX)

SET(CMAKE_POSITION_INDEPENDENT_CODE ON)
SET(CMAKE_CXX_STANDARD 23)

SET(ASYNC_FUNCTION_EXECUTION_VERSION 1.0.0)

FIND_PACKAGE(CMLIB
        COMPONENTS CMDEF CMUTIL
        REQUIRED
)

INCLUDE(GNUInstallDirs)

SET(ASYNC_FUNCTION_EXECUTION_TARGET_NAME async-function-execution)

OPTION(BRINGAUTO_SAMPLES OFF)
OPTION(BRINGAUTO_PACKAGE "Package creation" OFF)
OPTION(BRINGAUTO_INSTALL "Enable install" OFF)
OPTION(BRINGAUTO_SYSTEM_DEP "Enable system dependencies" OFF)
OPTION(BRINGAUTO_TESTS "Enable tests" OFF)

IF (NOT BRINGAUTO_SYSTEM_DEP)
    FIND_PACKAGE(CMLIB
            COMPONENTS STORAGE
            REQUIRED
    )
    INCLUDE(cmake/Dependencies.cmake)
ENDIF ()

IF (BRINGAUTO_PACKAGE)
    IF (NOT BRINGAUTO_INSTALL)
        SET(BRINGAUTO_INSTALL ON CACHE BOOL "Forced install due to BRINGAUTO_PACKAGE=ON" FORCE)
        MESSAGE(WARNING "BRINGAUTO_INSTALL is switched to on because of BRINGAUTO_PACKAGE=ON")
    ENDIF ()
ENDIF ()

FIND_PACKAGE(aeron         1.48.6 REQUIRED)

FILE(GLOB_RECURSE source_files ${CMAKE_CURRENT_LIST_DIR}/source/*)

CMDEF_ADD_LIBRARY(
        LIBRARY_GROUP ${ASYNC_FUNCTION_EXECUTION_TARGET_NAME}
        TYPE SHARED
        SOURCES ${source_files}
        INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include/"
        INSTALL_INCLUDE_DIRECTORIES "include/"
        VERSION ${ASYNC_FUNCTION_EXECUTION_VERSION}
)

TARGET_LINK_LIBRARIES(${ASYNC_FUNCTION_EXECUTION_TARGET_NAME}-shared PUBLIC
    aeron::aeron_client_wrapper
    aeron::aeron
    aeron::aeron_client_shared
    aeron::aeron_driver
)

IF(BRINGAUTO_TESTS)
    ENABLE_TESTING()
    ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/test)
    INCLUDE(CTest)
ENDIF(BRINGAUTO_TESTS)

IF (BRINGAUTO_INSTALL)
    CMDEF_INSTALL(
            TARGET ${ASYNC_FUNCTION_EXECUTION_TARGET_NAME}-shared
            NAMESPACE ${ASYNC_FUNCTION_EXECUTION_TARGET_NAME}-shared::
    )
ENDIF ()

IF (BRINGAUTO_PACKAGE)
    CMDEF_PACKAGE(
            MAIN_TARGET ${ASYNC_FUNCTION_EXECUTION_TARGET_NAME}-shared
            VERSION ${ASYNC_FUNCTION_EXECUTION_VERSION}
    )
    SET(CPACK_GENERATOR ZIP)
    SET(CPACK_PACKAGE_CONTACT "BringAuto s.r.o. <maintainers@bringauto.com>")
    INCLUDE(CPack)
ENDIF ()

IF (BRINGAUTO_SAMPLES)
    ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/examples)
ENDIF ()
